// Generated by CoffeeScript 1.10.0
$('body').on('click', '.form-step-2 .email-btn', function() {
  var _btn, _email, _url;
  _btn = $(this);
  _email = _btn.html().split('@')[1].split('.')[0];
  _url = '';
  switch (_email) {
    case 'hotmail':
      _url = "www." + _email + ".com";
      break;
    case 'yahoo':
      _url = "login." + _email + ".com";
      break;
    case 'gmail':
      _url = "mail.google.com";
      break;
    default:
      _url = "mail." + _email + ".com";
  }
  _url = "http://" + _url;
  return window.open(_url, '_blank');
});
